[package]
name = "solshield"
version = "0.1.0"
description = "SolShield - On-chain flagged wallet registry for Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solshield"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
